version: '3'
services:

  db:
    restart: always
    image: postgres:11-alpine
    network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - /pg11/data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    command: "postgres -c config_file=/etc/postgresql.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
