version: '3'
services:

  db:
    restart: always
    image: postgres:10-alpine
    network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/pleroma/postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
